/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dealership.ui;

import java.awt.Point;

/**
 *
 * @author krist
 */
public class CreateAccount extends javax.swing.JFrame {

    // user email and password
    private String userEmail = "";
    private char[] userPassword;
    
    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        userPassword = new char[20];
        warningLabel.setVisible(false);
    }
    
    // Gets previous frame's location on screen
    public void getPreviousFrameLocation(Point previous) {
        this.setLocation(previous);
    }
    
    // check if password is present
    private boolean checkPasswordPresent() {
        int blanks = 0;
        for (int i = 0; i < userPassword.length; i++) {
            if (userPassword[i] == 0)
                blanks++;
        }
        if (blanks == userPassword.length)
            return false;
        else
            return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        createAccountLabel = new javax.swing.JLabel();
        userInputPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        zipInput = new javax.swing.JTextField();
        stateInput = new javax.swing.JComboBox<>();
        streetLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        makeAccountButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Car Dealership");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 205, 49));

        createAccountLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        createAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountLabel.setText("Create Account");
        jPanel1.add(createAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 168, 41));

        userInputPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailLabel.setText("Email");
        userInputPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 55, -1));

        emailInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        userInputPanel.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 209, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwordLabel.setText("Password");
        userInputPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        passwordInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        userInputPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 209, -1));

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        firstNameLabel.setText("First Name");
        userInputPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        firstNameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameInputActionPerformed(evt);
            }
        });
        userInputPanel.add(firstNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 209, -1));

        zipLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        zipLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        zipLabel.setText("ZIP");
        userInputPanel.add(zipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        lastNameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });
        userInputPanel.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 209, -1));

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lastNameLabel.setText("Last Name");
        userInputPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        phoneInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneInputActionPerformed(evt);
            }
        });
        userInputPanel.add(phoneInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 209, -1));

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phoneLabel.setText("Phone #");
        userInputPanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        zipInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zipInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipInputActionPerformed(evt);
            }
        });
        userInputPanel.add(zipInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 70, -1));

        stateInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stateInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CA", "AL", "AK", "AZ", "AR", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));
        stateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateInputActionPerformed(evt);
            }
        });
        userInputPanel.add(stateInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        streetLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        streetLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        streetLabel.setText("Street");
        userInputPanel.add(streetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        stateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        stateLabel.setText("State");
        userInputPanel.add(stateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        addressInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressInputActionPerformed(evt);
            }
        });
        userInputPanel.add(addressInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 209, -1));

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addressLabel.setText("Address");
        userInputPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        makeAccountButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makeAccountButton.setText("Create Account");
        makeAccountButton.setToolTipText("Create account");
        makeAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeAccountButtonActionPerformed(evt);
            }
        });
        userInputPanel.add(makeAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 47));

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Go back to login");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        userInputPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 47));

        jPanel1.add(userInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 470, 320));

        warningLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel.setText("Please enter a");
        warningLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
        userEmail = emailInput.getText();
    }//GEN-LAST:event_emailInputActionPerformed

    private void makeAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeAccountButtonActionPerformed
        // TODO add your handling code here:
        boolean passwordPresent = checkPasswordPresent();
        if (userEmail.equals("") && (passwordPresent == false)) {
            warningLabel.setText("Press ENTER \nin each input box to register input");
            warningLabel.setVisible(true);
        } 
        else if (userEmail.equals("") && (passwordPresent == true)) {
            warningLabel.setText("Please enter an email");
            warningLabel.setVisible(true);
        }
        else if ((passwordPresent == false) && (!userEmail.equals(""))) {
            warningLabel.setText("Please enter a password");
            warningLabel.setVisible(true);
        }
        else {
            
        }
    }//GEN-LAST:event_makeAccountButtonActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
        userPassword = passwordInput.getPassword();
    }//GEN-LAST:event_passwordInputActionPerformed

    private void firstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameInputActionPerformed

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void phoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneInputActionPerformed

    private void zipInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipInputActionPerformed

    private void stateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateInputActionPerformed

    private void addressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressInputActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        LoginScreen login = new LoginScreen();
        login.getPreviousFrameLocation(this.getLocationOnScreen());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton makeAccountButton;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JComboBox<String> stateInput;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel userInputPanel;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JTextField zipInput;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
