/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dealership.ui;

import java.awt.Point;

public class EditAccountScreen extends javax.swing.JFrame {

    /**
     * Creates new form EditAccountScreen
     */
    public EditAccountScreen() {
        initComponents();
    }
    
    // Gets previous frame's location on screen
    public void getPreviousFrameLocation(Point previous) {
        this.setLocation(previous);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        userInputPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        zipInput = new javax.swing.JTextField();
        stateInput = new javax.swing.JComboBox<>();
        streetLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        streetInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        saveEditsButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Edit Account Details");

        userInputPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailLabel.setText("Email");
        userInputPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 55, -1));

        emailInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 209, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwordLabel.setText("Password");
        userInputPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        passwordInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 209, -1));

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        firstNameLabel.setText("First Name");
        userInputPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        firstNameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(firstNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 209, -1));

        zipLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        zipLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        zipLabel.setText("ZIP");
        userInputPanel.add(zipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        lastNameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 209, -1));

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lastNameLabel.setText("Last Name");
        userInputPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        phoneInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(phoneInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 209, -1));

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phoneLabel.setText("Phone #");
        userInputPanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        zipInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(zipInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 70, -1));

        stateInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stateInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CA", "AL", "AK", "AZ", "AR", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));
        userInputPanel.add(stateInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        streetLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        streetLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        streetLabel.setText("Street");
        userInputPanel.add(streetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        stateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        stateLabel.setText("State");
        userInputPanel.add(stateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        streetInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInputPanel.add(streetInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 209, -1));

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addressLabel.setText("Address");
        userInputPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        saveEditsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveEditsButton.setText("Save Changes");
        saveEditsButton.setToolTipText("Create account");
        saveEditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditsButtonActionPerformed(evt);
            }
        });
        userInputPanel.add(saveEditsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 170, 47));

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Go back to login");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        userInputPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 47));

        signOutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signOutButton.setText("Sign Out");
        signOutButton.setToolTipText("Go back to login");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        userInputPanel.add(signOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, 47));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(userInputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveEditsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditsButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_saveEditsButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        MainFrame ms = new MainFrame();
        ms.getPreviousFrameLocation(this.getLocationOnScreen());
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signOutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton saveEditsButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JComboBox<String> stateInput;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetInput;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel userInputPanel;
    private javax.swing.JTextField zipInput;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
