/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dealership.ui;

import dealership.controller.AccountHandler;
import dealership.controller.VehicleHandler;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krist
 */
public class MakeAppointment extends javax.swing.JDialog {

    // month list
    private final String[] MONTH_LIST = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
    // current year
    private int year;

    private final JTable appointmentTable;
    
    /**
     * Creates new form makeAppt
     * @param parent Screen that JDialog is attached to
     * @param modal True if frame can be used while JDialog is in use, false otherwise
     */
    public MakeAppointment(java.awt.Frame parent, boolean modal, JTable appointmentTable) {
        super(parent, modal);
        this.appointmentTable = appointmentTable;
        initComponents();
        vehicleText.setText(VehicleHandler.getSelectedVehicleDetails());
        loadDatesForNextTwoWeeks();
        //setCurrentMonthDate();
    }

   private void loadDatesForNextTwoWeeks() {
       LocalDateTime dateTime = LocalDateTime.now().plusDays(1);
       for (int day = 1; day <= 14; day++) {
           dateSelect.addItem(dateTime.format(DateTimeFormatter.ofPattern("EEEE, MMM d", Locale.ENGLISH)));
           dateTime = dateTime.plusDays(1);
       }
    }

    /*
    // set options to today's date
    private void setCurrentMonthDate() {
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("MMMM dd YYYY", Locale.ENGLISH);
        String month = dateFormat.format(LocalDate.now()).substring(0, dateFormat.format(LocalDate.now()).indexOf(" "));
        String date = dateFormat.format(LocalDate.now()).substring(dateFormat.format(LocalDate.now()).indexOf(" ") + 1, dateFormat.format(LocalDate.now()).lastIndexOf(" "));
        String yearString = dateFormat.format(LocalDate.now()).substring(dateFormat.format(LocalDate.now()).lastIndexOf(" ") + 1);
        year = Integer.parseInt(yearString);
    }
    
    // change month to int number
    private int monthNameToInt(String monthName) {
        int monthNum = 0;
        for (int i = monthNum; i < MONTH_LIST.length; i++) {
            if (monthName.equals(MONTH_LIST[i]))
                monthNum = i + 1;
        }
        return monthNum;
    }
    
    // set number of days in date combo box
   /* private void setNumDays(String monthName, String date, int year) {
        YearMonth ym = YearMonth.of(year, monthNameToInt(monthName));
        int numOfDays = ym.lengthOfMonth();
        ArrayList<String> days = new ArrayList<>();
        for (int i = 1; i <= numOfDays; i++)
            days.add(String.valueOf(i));
        daySelect.setModel(new DefaultComboBoxModel<>(new Vector<>(days)));
        if (date == null)
            daySelect.getModel().setSelectedItem("1");
        else {
            if (Integer.parseInt(date) > numOfDays)
                daySelect.getModel().setSelectedItem("1");
            else
                daySelect.getModel().setSelectedItem(date);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        dateSelect = new javax.swing.JComboBox<>();
        monthLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeSelect = new javax.swing.JComboBox<>();
        vehicleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleText = new javax.swing.JTextPane();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("🚗 Schedule a Test Drive");

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Create account");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        dateSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        monthLabel.setText("Date");

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeLabel.setText("Time");

        timeSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00 AM - 09:00 AM", "09:00 AM - 10:00 AM", "10:00 AM - 11:00 AM", "11:00 AM - 12:00 PM", "12:00 PM - 01:00 PM", "01:00 PM - 02:00 PM", "02:00 PM - 03:00 PM", "03:00 PM - 04:00 PM", "04:00 PM - 05:00 PM", "05:00 PM - 06:00 PM", "06:00 PM - 07:00 PM" }));

        vehicleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehicleLabel.setText("Vehicle");

        vehicleText.setEditable(false);
        vehicleText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(vehicleText);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addComponent(dateSelect, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(vehicleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(monthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("Create account");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (AccountHandler.tryMakeAppointment(VehicleHandler.getSelectedVehicleVin(),
                AccountHandler.formatDateTime(String.valueOf(dateSelect.getSelectedItem()), String.valueOf(timeSelect.getSelectedItem())))) {
            JOptionPane.showMessageDialog(this, "Appointment made!", "Success", JOptionPane.ERROR_MESSAGE);
            AccountHandler.loadAppointmentsIntoTable((DefaultTableModel) appointmentTable.getModel());
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to make an appointment. Please try another date/time.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> dateSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox<String> timeSelect;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JTextPane vehicleText;
    // End of variables declaration//GEN-END:variables
}
